# Azure Pipeline
# https://aka.ms/yaml
#
# stage -* job -* step~=task
#   |-build
#   |-release
#
# each job will run in parallel

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: restore
    projects: '*.sln'
    verbosityRestore: Minimal
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 1 }

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '*.sln'
    arguments: --configuration:Release
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }

- task: DotNetCoreCLI@2
  displayName: Tests (net48)
  inputs:
    command: custom
    custom: dotcover
    arguments: >
      --dcOutput=..\coverage\net48.dcvr
      --dcFilters=+:Sharp.Disposable;+:Sharp.Disposable.*;-:*.Tests
      --dcAttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute
      test
      --framework:net48
      --configuration:Release
      --no-build
    nobuild: true
    testRunTitle: net48
    workingDirectory: Sharp.Disposable.Tests
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }

- task: DotNetCoreCLI@2
  displayName: Tests (netcoreapp3.1)
  inputs:
    command: custom
    custom: dotcover
    arguments: >
      --dcOutput=..\coverage\netcoreapp3.1.dcvr
      --dcFilters=+:Sharp.Disposable;+:Sharp.Disposable.*;-:*.Tests
      --dcAttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute
      test
      --framework:netcoreapp3.1
      --configuration:Release
      --no-build
    nobuild: true
    testRunTitle: netcoreapp3.1
    workingDirectory: Sharp.Disposable.Tests
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }

- task: PowerShell@2
  displayName: Coverage Report
  inputs:
    filePath: Make.ps1
    arguments: -MergeCoverage

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/dist/*.nupkg'
    nuGetFeedType: internal
    publishVstsFeed: 3b77dcda-0977-4777-b897-54aec427b170
    verbosityPush: Normal
