# Azure Pipeline
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*.sln'
    verbosityRestore: 'Minimal'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.sln'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Sharp.Disposable.Tests/*.csproj'
    arguments: '--framework net45'
    testRunTitle: 'net45'
    workingDirectory: 'Sharp.Disposable.Tests'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Sharp.Disposable.Tests/*.csproj'
    arguments: '--framework netstandard1.1'
    testRunTitle: 'net45'
    workingDirectory: 'Sharp.Disposable.Tests'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
