# Azure Pipeline
# https://aka.ms/yaml
#
# stage -* job -* step~=task
#   |-build
#   |-release
#
# each job will run in parallel

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: 'restore'
    projects: '*.sln'
    verbosityRestore: 'Minimal'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 1 }
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '*.sln'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
- task: DotNetCoreCLI@2
  displayName: Tests (net45)
  inputs:
    command: 'test'
    projects: '*.csproj'
    arguments: '--framework net45'
    testRunTitle: 'net45'
    workingDirectory: 'Sharp.Disposable.Tests'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
- task: DotNetCoreCLI@2
  displayName: Tests (netstandard1.1)
  inputs:
    command: 'test'
    projects: '*.csproj'
    arguments: '--framework netstandard1.1'
    testRunTitle: 'net45'
    workingDirectory: 'Sharp.Disposable.Tests'
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
