# Azure Pipeline
# https://aka.ms/yaml
#
# stage -* job -* step~=task
#   |-build
#   |-release
#
# each job will run in parallel

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: restore
    projects: '*.sln'
    verbosityRestore: Minimal
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 1 }

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '*.sln'
    arguments: --configuration:Release
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }

- task: DotNetCoreCLI@2
  displayName: Tests (net45)
  inputs:
    command: custom
    custom: dotcover
    arguments: >
      --dcOutput=..\coverage\net45.dcvr
      --dcFilters=+:Sharp.Disposable;+:Sharp.Disposable.*;-:*.Tests
      --dcAttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute
      test
      --framework:net45
      --configuration:Release
    nobuild: true
    testRunTitle: net45
    workingDirectory: Sharp.Disposable.Tests
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }

- task: DotNetCoreCLI@2
  displayName: Tests (netstandard1.1)
  inputs:
    command: custom
    custom: dotcover
    arguments: >
      --dcOutput=..\coverage\netstandard1.1.dcvr
      --dcFilters=+:Sharp.Disposable;+:Sharp.Disposable.*;-:*.Tests
      --dcAttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute
      test
      --framework:netstandard1.1
      --configuration:Release'
    nobuild: true
    testRunTitle: netstandard1.1
    workingDirectory: Sharp.Disposable.Tests
  env: { DOTNET_CLI_TELEMETRY_OPTOUT: 0 }
